import "@/styles/globals.css";
import AppWrapper from "@/components/AppWrapper";
import { headers } from "next/headers";
import { Session } from "next-auth";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getSession(headers().get("cookie") ?? "");
    return (
        <html lang="en">
            <body>
                <AppWrapper session={session}>{children}</AppWrapper>
            </body>
        </html>
    );
}
async function getSession(cookie) {
    const response = await fetch(
        `${process.env.NEXTAUTH_URL}/api/auth/session`,
        {
            headers: {
                cookie,
            },
        }
    );
    const session = await response.json();

    return Object.keys(session).length > 0 ? session : null;
}
